Linux/Android: MessageQ - Fix Implicit Declaration Warning
This patch fixes the following compiler warning:

    lad.c:685:17: warning: implicit declaration of function 'MessageQ_announce'

This patch adds the MessageQ_announce prototype to MessageQ.h so
that MessageQ_announce is no longer implicitly declared.

Signed-off-by: Angela Stegmaier <angelabaker@ti.com>