Enable Examples Compilation with C++ Compiler
Attempting to compile the examples and tests in Linux with
the c++ compiler resulted in the following errors:

In file included from MessageQApp.c:46:0:
../../../packages/ti/ipc/Ipc.h:148:22: error: ‘<anonymous>’ has incomplete type
../../../packages/ti/ipc/Ipc.h:148:26: error: invalid use of ‘Void {aka void}’

In file included from ../../../linux/include/_lad.h:50:0,
                 from ../../../linux/include/ladclient.h:58,
                 from LAD_client.c:48:
../../../linux/include/_GateMP.h:78:3: error: conflicting declaration 'typedef struct GateMP_Object GateMP_Object'
In file included from ../../../linux/include/_lad.h:49:0,
                 from ../../../linux/include/ladclient.h:58,
                 from LAD_client.c:48:
../../../packages/ti/ipc/GateMP.h:222:16: error: 'struct GateMP_Object' has a previous declaration as 'struct GateMP_Object

This patch fixes these compilation issues so that the Linux examples can
be compiled with c++. Note that this patch does not have complete
changes to allow IPC to be compiled using the c++ compiler, but only
the examples.

Signed-off-by: Angela Stegmaier <angelabaker@ti.com>